In [160]:
import numpy as np
import numpy as onp

In [161]:

def nan_concat_leading_windows(x):
    n = len(x)
    add_arr = np.full(n - 1, np.nan)
    x_ext = np.concatenate((add_arr, x[::-1]))
    strided = np.lib.stride_tricks.as_strided
    nrows = len(x_ext) - n + 1
    s = x_ext.strides[0]
    return strided(x_ext, shape=(nrows, n), strides=(s, s))[::-1, ::-1]


def nan_concat_lagging_windows(x):
    n = len(x)
    add_arr = np.full(n - 1, np.nan)
    x_ext = np.concatenate((add_arr, x))[::-1]
    strided = np.lib.stride_tricks.as_strided
    nrows = len(x_ext) - n + 1
    s = x_ext.strides[0]
    return strided(x_ext, shape=(nrows, n), strides=(s, s))[::-1, ::-1]


def nan_concat_lagging_windows(x):
    n = len(x)
    add_arr = onp.full(n - 1, onp.nan)
    x_ext = onp.concatenate((add_arr, x))
    strided = onp.lib.stride_tricks.as_strided
    nrows = len(x_ext) - n + 1
    s = x_ext.strides[0]
    return strided(x_ext, shape=(nrows, n), strides=(s, s))[:, :]



In [162]:
x = np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [163]:
x1 = nan_concat_leading_windows(x)
x2 = nan_concat_lagging_windows(x)

In [164]:
x1

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., nan],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        nan, nan],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., nan,
        nan, nan],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., nan, nan,
        nan, nan],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., nan, nan, nan,
        nan, nan],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., nan, nan, nan, nan,
        nan, nan],
       [ 7.,  8.,  9., 10., 11., 12., 13., 14., nan, nan, nan, nan, nan,
        nan, nan],
       [ 8.,  9., 10., 11., 12., 13., 14., nan, nan, nan, nan, nan, nan,
        nan, nan],
       [ 9., 10., 11., 12., 13., 14., nan, nan, nan, nan, nan, nan, nan,
        nan, nan],
       [10., 11., 12., 13., 14., nan, nan, nan, nan, nan, nan, nan, nan,
       

In [165]:
x2

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan,  0.],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         0.,  1.],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,  0.,
         1.,  2.],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,  0.,  1.,
         2.,  3.],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,  0.,  1.,  2.,
         3.,  4.],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan,  0.,  1.,  2.,  3.,
         4.,  5.],
       [nan, nan, nan, nan, nan, nan, nan, nan,  0.,  1.,  2.,  3.,  4.,
         5.,  6.],
       [nan, nan, nan, nan, nan, nan, nan,  0.,  1.,  2.,  3.,  4.,  5.,
         6.,  7.],
       [nan, nan, nan, nan, nan, nan,  0.,  1.,  2.,  3.,  4.,  5.,  6.,
         7.,  8.],
       [nan, nan, nan, nan, nan,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,
         8.,  9.],
       [nan, nan, nan, nan,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
       

In [86]:
a = np.arange(100).reshape(10, 10)

In [88]:
np.diag(x2)

array([nan, nan, nan, nan, nan, nan, nan,  0.,  2.,  4.,  6.,  8., 10.,
       12., 14.])

In [170]:
x2[:, -1, None]

array([[ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.],
       [11.],
       [12.],
       [13.],
       [14.]])

In [172]:
diff = x2[:, -1, None] - x2

In [176]:
x3 = onp.where(diff <= 3, x2, onp.nan)

In [178]:
onp.nanmax(x3, axis=1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [179]:
onp.nanmax(np.array([np.nan, np.nan]))

/tmp/ipykernel_102606/3014938994.py:1: RuntimeWarning: All-NaN slice encountered
  onp.nanmax(np.array([np.nan, np.nan]))


nan

In [180]:
onp.nan > 3

False

In [187]:
x = np.array([0, 0, 0, 1, 1, 0, 0])
diff = np.hstack((0, x[1:] - x[:-1]))
jumps = np.where(diff != 0, 1, 0)
jumps

array([0, 0, 0, 1, 0, 1, 0])

In [193]:
y = np.where(jumps!=0, 1, 0)
y

array([0, 0, 0, 1, 0, 1, 0])

In [196]:
np.argwhere(y).flatten().tolist()

[3, 5]

array([0, 0, 1, 0, 1, 0])

In [7]:
import equinox as eqx
import jax.random as jrand
import jax.numpy as jnp

In [6]:
mlp = eqx.nn.MLP(in_size=5,
                out_size=0,
                key=jrand.PRNGKey(0),
                width_size=5,
                depth=3)

In [8]:
mlp(jnp.arange(5))

Array([], dtype=float32)

In [2]:
?eqx.nn.MLP